# Trading System Configuration
system:
  name: "crypto_trading_system"
  version: "1.0.0"
  environment: "development"  # development, staging, production
  
# Data Sources Configuration
data_sources:
  crypto:
    coinbase:
      enabled: true
      base_url: "https://api.exchange.coinbase.com"
      websocket_url: "wss://ws-feed.exchange.coinbase.com"
      sandbox_mode: true
      rate_limit: 10  # requests per second
      symbols:
        - "BTC-USD"
        - "ETH-USD"
        - "SOL-USD"
        - "ADA-USD"
        - "DOT-USD"
        - "AVAX-USD"
    
    binance:
      enabled: false
      base_url: "https://api.binance.com"
      websocket_url: "wss://stream.binance.com:9443"
      testnet: true
      rate_limit: 20
      symbols:
        - "BTCUSDT"
        - "ETHUSDT"
        - "SOLUSDT"
  
  stocks:
    alpaca:
      enabled: true
      base_url: "https://paper-api.alpaca.markets"
      data_url: "https://data.alpaca.markets"
      websocket_url: "wss://stream.data.alpaca.markets"
      paper_trading: true
      symbols:
        - "AAPL"
        - "GOOGL"
        - "MSFT"
        - "TSLA"
        - "NVDA"

# Alpha Models Configuration
alpha_models:
  # Existing models
  mean_reversion:
    enabled: true
    lookback_minutes: 20
    min_samples: 10
    z_score_cap: 3.0
    edge_scaling: 5.0
    target_symbols: ["AAPL", "GOOGL", "MSFT", "TSLA", "NVDA"]
  
  momentum_fast:
    enabled: true
    fast_period: 5
    slow_period: 20
    min_samples: 25
    edge_scaling: 10.0
    target_symbols: ["BTC-USD", "ETH-USD", "SOL-USD"]
  
  # New alpha models (A1-1, A1-2)
  ob_pressure:
    enabled: true
    model_name: "ob_pressure_v0"
    edge_scaling: 25.0
    min_confidence: 0.50
    max_confidence: 1.0
    target_symbols: ["BTC-USD", "ETH-USD", "SOL-USD", "ADA-USD", "DOT-USD", "AVAX-USD"]
    description: "Order-Book-Pressure Alpha: Edge = 25 * pressure where pressure = (bid_size - ask_size) / (bid_size + ask_size + 1e-9)"
  
  ma_momentum:
    enabled: true
    model_name: "ma_momentum_v0"
    short_period: 5
    long_period: 30
    min_samples: 30
    edge_scaling: 40.0
    min_confidence: 0.55
    max_confidence: 0.9
    target_symbols: ["BTC-USD", "ETH-USD", "SOL-USD", "ADA-USD", "DOT-USD", "AVAX-USD"]
    description: "Moving-Average Momentum Alpha: Edge = 40 * z where z = (ma_short - ma_long) / ma_long, capped at ±40 bp"

# Ensemble Configuration (A2-1)
ensemble:
  meta_learner:
    enabled: true
    model_name: "meta_learner_v0"
    method: "logistic_blend"  # logistic_blend, random_forest, simple_average
    
    # Logistic blending configuration
    logistic_weights:
      w1: 1.0  # OBP weight
      w2: 1.0  # MAM weight
    
    # RandomForest configuration (fallback)
    random_forest:
      n_estimators: 100
      max_depth: 10
      random_state: 42
      n_jobs: -1
    
    # Training configuration
    training:
      min_samples: 10
      retrain_interval_hours: 24
      validation_split: 0.2

# Position Sizing Configuration
position_sizing:
  kelly:
    enabled: true
    max_position_pct:
      stocks: 0.25  # 25% max position for stocks
      crypto: 0.20  # 20% max position for crypto
    min_edge_bps: 5.0
    max_leverage:
      stocks: 1.0
      crypto: 3.0
    risk_free_rate: 0.02

# Risk Management Configuration
risk_management:
  basic_risk_manager:
    enabled: true
    
    # Global limits
    max_total_exposure: 1000000  # $1M total exposure
    max_daily_loss: 50000       # $50K daily loss limit
    max_drawdown: 0.15          # 15% max drawdown
    
    # Asset-specific limits
    stocks:
      max_position_size: 250000  # $250K per stock position
      max_sector_exposure: 500000  # $500K per sector
      max_daily_trades: 100
    
    crypto:
      max_position_size: 100000   # $100K per crypto position
      max_exchange_exposure: 500000  # $500K per exchange
      max_crypto_drawdown: 0.05   # 5% crypto-specific drawdown
      max_crypto_leverage: 3.0    # 3x max leverage for crypto
      max_daily_trades: 50

# Execution Configuration
execution:
  # Stocks execution
  alpaca:
    enabled: true
    mode: "paper"  # paper, live
    order_type: "market"
    time_in_force: "day"
    
  # Crypto execution
  coinbase:
    enabled: true
    mode: "paper"  # paper, live
    order_type: "market"
    time_in_force: "gtc"  # good till canceled
    fee_rate: 0.005  # 0.5% fee

# Monitoring Configuration
monitoring:
  metrics:
    enabled: true
    update_interval_seconds: 60
    
  logging:
    level: "INFO"
    file: "logs/trading_system.log"
    max_size_mb: 100
    backup_count: 5
    
  alerts:
    enabled: true
    email:
      enabled: false
      smtp_server: "smtp.gmail.com"
      smtp_port: 587
    
    slack:
      enabled: false
      webhook_url: ""
    
    risk_alerts:
      max_drawdown_threshold: 0.10
      large_position_threshold: 100000
      unusual_pnl_threshold: 10000

# Backtesting Configuration
backtesting:
  enabled: true
  start_date: "2024-01-01"
  end_date: "2024-12-31"
  initial_capital: 1000000
  commission_rate: 0.001
  slippage_bps: 2.0

# Performance Targets
performance_targets:
  alpha_models:
    min_hit_rate: 0.55
    min_sharpe_ratio: 1.5
    max_drawdown: 0.10
    
  ensemble:
    min_hit_rate: 0.60
    min_sharpe_ratio: 2.0
    max_drawdown: 0.08
    
  system:
    target_annual_return: 0.20
    target_sharpe_ratio: 2.5
    max_annual_drawdown: 0.12 